### ISSUE TITLE
UI not rendered in syphon

### ISSUE THREAD

**Issue by donuan** [keijiro/Funnel#10]
The UI does not get passed along in the Syphon render.
Is there a possible workaround for this?

**Comment by donuan** [comment]
Anyway thanks a bunch for the plugin! Great job and very useful.

**Comment by keijiro** [comment]
Are you using the new UI system or the old one (IMGUI with OnGUI)?

I'm pretty sure that the new UI system is supported with Funnel, but not sure about IMGUI.

**Comment by donuan** [comment]
I am using the Canvas based UI.

**Comment by delaurean** [comment]
Hi there! Thanks keijiro for this amazing asset.
@donuan  did you get to send de UI over syphon?
cheers from Argentina.

**Comment by donuan** [comment]
@delaurean unfortunately not. its been on my todo to try to look into a bit deeper. let me know if you find a way.

**Comment by delaurean** [comment]
@donuan  So far...
You got 3 Render Modes on Canvas.
1- Screen Space : Overlay (not working over syphon/funnel)
2- Screen Space : Camera .. The canvas image is rendered inside your mail camera so it  Works really fine if your camera over Syphon / funnel. If your camera is static, everithing is ok , but if the camera is moving the canvas has a flickiring bug when moving the camera around worldspace.  https://forum.unity3d.com/threads/screen-space-camera-canvas-has-choppy-ui-when-camera-moves.263791/ There are some solutions over there.
3- World Space: Everithing is ok over syphon. If you want the camera to move, you have to make the canvas, child of the camera, and try to find a way to put the canvas on top. cause some 3d graphics are overlapping the canvas image. 
;)

**Comment by keijiro** [comment]
I'm going to discontinue this plugin (Funnel) because I started working on the new plugin (KlakSyphon).

https://github.com/keijiro/KlakSyphon

Please consider migrating to the new plugin for future support.

I'm closing this issue. Please feel free to reopen for further questions.
