### ISSUE TITLE
hang when building an app with funnel

### ISSUE THREAD

**Issue by AMCB** [keijiro/Funnel#13]
First thanks again for your incredible work Keijiro!
I'm trying to integrate Unity in our workflow for live performances, however it's not as straightforward as I'd like.
Using funnel to bypass the lack of multiscreen support in unity for Mac would be a great workaround. Unfortunately it hangs when building an app that has an activated funnel script…

**Comment by keijiro** [comment]
- Please check if you're using the latest version of Unity.
- Please check if the target architecture is set to x86_64. Funnel doesn't support 32-bit.

**Comment by AMCB** [comment]
Thanks a lot for your answer, I'm building in x86_64 with 2017.2.0f3 (the last stable release).

**Comment by keijiro** [comment]
Thanks for the clarification. So, it seems to be an unknown bug. I'll check it later.

**Comment by AMCB** [comment]
It seems to happen randomly in the Editor also when `Maximize on play is active` : it hangs just after play is pressed.
So maybe it's a Nvidia driver issue related to the initialisation of an OpenGL Context.
I'll try on a regular Mac ASAP.

**Comment by bottleleong** [comment]
Hello Keijiro! I have the same problem also. The app will hang when I am trying to receive the frame via Arena or Madmapper.(It wont hang when I am testing with unity editor.)

**Comment by avseoul** [comment]
In my case, it's fixed when I manually set the graphics api in player settings from metal to core opengl. Hope this helps. 

unity 2017.1.1f1 / osx 10.12.6 

![screen shot 2017-12-01 at 11 22 24 am](https://user-images.githubusercontent.com/3428464/33492035-f2c145da-d689-11e7-92bf-e541371da4e6.png)

**Comment by keijiro** [comment]
I'm going to discontinue this plugin (Funnel) because I started working on the new plugin (KlakSyphon).

https://github.com/keijiro/KlakSyphon

Please consider migrating to the new plugin to get better stability and future support.

I'm closing this issue. Please feel free to reopen for further questions.
