### ISSUE TITLE
No Syphon on build - where to change architecture

### ISSUE THREAD

**Issue by vibber** [keijiro/Funnel#15]
I can understand that you have to build for 64bit to have the Funnel plugin included. However in the latest Unity I cannot find anywhere to set the architecture to 64bit. What to do?

**Comment by keijiro** [comment]
AFAIK, macOS 32-bit support has been deprecated. So there is no option to switch the architecture -- it's always 64-bit.

**Comment by vibber** [comment]
Well the problem is there nevertheless. The plugin is not included in the build.

(I think you're wrong by the way, when I get info on the app it says 'open in low resolution' which AFAIK means it's a universal binary)
