### ISSUE TITLE
DllNotFoundException using unity 2019

### ISSUE THREAD

**Issue by drakomatic** [keijiro/Funnel#17]
![image](https://user-images.githubusercontent.com/79185478/123501447-3a389f00-d602-11eb-84aa-931bd97bd244.png)

**Comment by drakomatic** [comment]
i have no idea how to fix this and ive tried a ton of stuff

**Comment by keijiro** [comment]
hidapi.dll is something for interacting with HID (human interface device)like controllers, mouse and keyboard. It's not related to Funnel.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
