### ISSUE TITLE
Glichy syphon image using reflection probes

### ISSUE THREAD

**Issue by VisualBoy** [keijiro/Funnel#2]
Hi Keijiro,
I'm issuing some strange artifacts on syphon output when in a scene there is a reflection probe (realtime, refresh every frame). Sometimes image render correct, but still a flickering render problem:

![off](https://cloud.githubusercontent.com/assets/443705/10151975/9490ed48-664d-11e5-96ba-9ff5c8f909d9.png)
 
If I turn off reflection probe... Funnel works well:

![on](https://cloud.githubusercontent.com/assets/443705/10152018/d69771bc-664d-11e5-8a2d-3ea5cd687cca.png)

Funnel version: latest
Unity version: 5.1.2
OS:  OSX 10.8.4

Thanks for your support!

**Comment by keijiro** [comment]
Sorry for the long delay in response. It seems to be fixed with the recent updates. Thanks!

**Comment by VisualBoy** [comment]
Thanks Keijiro!
