### ISSUE TITLE
Error Messages in Unity 5.2.2f1? 

### ISSUE THREAD

**Issue by jeanpoole** [keijiro/Funnel#3]
Hello - 
FYI - Funnel gives me these error messages in Unity 5.2.2f1.... 

Some scripts have compilation errors which may prevent obsolete API usages to get updated. Obsolete API updating will continue automatically after these errors get fixed.

Assets/Funnel/Funnel.cs(187,16): warning CS0618: `UnityEngine.GL.IssuePluginEvent(int)' is obsolete: `IssuePluginEvent(eventID) is deprecated. Use IssuePluginEvent(callback, eventID) instead.'

Assets/Funnel/Funnel.cs(213,16): warning CS0618: `UnityEngine.GL.IssuePluginEvent(int)' is obsolete: `IssuePluginEvent(eventID) is deprecated. Use IssuePluginEvent(callback, eventID) instead.'

Assets/Funnel/Funnel.cs(251,33): warning CS0618: `UnityEngine.Texture.GetNativeTextureID()' is obsolete: `Use GetNativeTexturePtr instead.'

Assets/Funnel/Funnel.cs(262,28): warning CS0618: `UnityEngine.Texture.GetNativeTextureID()' is obsolete: `Use GetNativeTexturePtr instead.'

Assets/Funnel/Funnel.cs(269,16): warning CS0618: `UnityEngine.GL.IssuePluginEvent(int)' is obsolete: `IssuePluginEvent(eventID) is deprecated. Use IssuePluginEvent(callback, eventID) instead.'

eflection.Emit.ModuleBuilder.Save () <0x00643>
  at System.Reflection.Emit.AssemblyBuilder.Save (string,System.Reflection.PortableExecutableKinds,System.Reflection.ImageFileMachine) <0x00660>
  at Mono.CSharp.CodeGen.Save (string,bool,Mono.CSharp.Report) <0x00093>
  at Mono.CSharp.Driver.Compile () <0x00d03>
  at Mono.CSharp.Driver.Main (string[]) <0x0008f>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0x00043>

Native stacktrace:

	0   libsystem_kernel.dylib              0x96caef96 __kill + 10
	1   libsystem_c.dylib                   0x9065fbf4 raise + 27
	2   mono                                0x0033a3ea g_assertion_message + 122
	3   mono                                0x0033a2d1 g_logv + 257
	4   mono                                0x0033a35b g_log + 59
	5   mono                                0x00285e79 mono_image_create_pefile + 12425
	6   mono                                0x00283dca mono_image_create_pefile + 4058
	7   mono                                0x001e3774 mono_register_jit_icall + 60052
	8   ???                                 0x0621920f 0x0 + 102863375
	9   ???                                 0x06218cb4 0x0 + 102862004
	10  ???                                 0x061a2009 0x0 + 102375433
	11  ???                                 0x061a1784 0x0 + 102373252
	12  ???                                 0x016afa34 0x0 + 23788084
	13  ???                                 0x004e12a8 0x0 + 5116584
	14  ???                                 0x004e162c 0x0 + 5117484
	15  mono                                0x00011dff mono_get_runtime_build_info + 6831
	16  mono                                0x0025f570 mono_runtime_invoke + 208
	17  mono                                0x0026a6c4 mono_runtime_exec_main + 836
	18  mono                                0x0026a35f mono_runtime_run_main + 543
	19  mono                                0x000b76be mono_jit_exec + 286
	20  mono                                0x000bae77 mono_main + 13959
	21  mono                                0x000b98f2 mono_main + 8450
	22  mono                                0x00001bd0 main + 64
	23  mono                                0x00001b45 start + 53

Debug info from gdb:

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

WriteFile returned 25

Some scripts have compilation errors which may prevent obsolete API usages to get updated. Obsolete API updating will continue automatically after these errors get fixed.

**Comment by keijiro** [comment]
There are two different issues.

Regarding the obsolete API warning, the new API is still broken (!!), and thus I can't update the plugin to use the new API. Please ignore these warning messages at the moment. It might be irritating... but I'm also irritated with it :)

Regarding the SIGSEGV crash -- are you using 32-bit x86 build? I'm not sure but the 32-bit OS X Unity player has some problems with the native plugin. Please try out the 64-bit x64 player.

I'll fix the former issue when the new API becomes available.

**Comment by jeanpoole** [comment]
Thanks for the feedback Keijiro - and sorry for bothering you... 

Unfortunately I cannot ignore the warning messages - because Unity brings up this message - "All compiler errors have to be fixed before you enter playmode" - when I try to press play and send out to syphon recorder / VDMX etc

Where does it say Unity is 32 or 64bit? I can't see any mention of it in 'about unity' or in the preferences... or in the release notes where I've downloaded it from... I am on version 5.2.2f1

thanks again...

**Comment by keijiro** [comment]
That's strange. Basically you can ignore all warning messages. I found a forum post about the same symptom.

http://forum.unity3d.com/threads/editor-showing-an-error-and-wont-run-game-for-compiler-warnings.357882/
http://forum.unity3d.com/threads/sometimes-unity-is-treating-c-compile-time-warnings-as-compile-time-errors.303451/

You can change the 32/64 build from this dropdown list:
<img width="486" alt="32-64" src="https://cloud.githubusercontent.com/assets/343936/11062066/0047dcdc-87ef-11e5-84db-e3f464dd5264.png">

**Comment by jeanpoole** [comment]
Thanks again - I tried a new project, and set it to x86_64 - then imported a funnel package - and it brought up the same error - not allowing me to play properly...  This happens with funnel.. and with syphon... but it has always happened for me with Unity the short time ive been using it - if any errors pop up in the console - i can no longer run it, until they are made to go ... which usually means i have to quit and start the project again... Any advice about how to avoid this would be great! (I didn't know it wasn't like this for everybody.. )

**Comment by keijiro** [comment]
That's a strange behavior. Recommended to resolve that anyway.

If you're using antivirus software, turn it off and check if the behavior changes.

Do you have admin privileges on the Mac? It's hardly relevant, but using Unity without admin rights might cause some issues. If you don't, try to add admin rights to your account.
https://ttlc.intuit.com/questions/1899267-administrator-rights-mac

**Comment by jeanpoole** [comment]
Thanks for the recommendations - I'm not running any antivirus software... and I do have admin privileges... 

.. any other ideas about how I could try to resolve this Unity behaviour on my machine?
((and for the record, it's a 15" MBP (retina, late 2013 - with a NVIDIA GeForce GT 750M 204MB card), 
running 10.10.5 )) 

thanks!

**Comment by keijiro** [comment]
According to the error message, it fails to write something into a file. Do you have enough free space in your drive?

Or are you using a file-syncing service like Dropbox? If you are, please turn it off or move the project outside of the service.

**Comment by jeanpoole** [comment]
THANK YOU KEIJIRO!  I've been running my Unity projects off an external drive... it has plenty of space - but I tried to run a new project off my laptop SSD - and this worked - ie I could both syphon and funnel - and it sent a signal to syphon recorder, even though there were error messages in the console... it just played anyway...   

not sure what the issue with the other drive is - but that's ok, I can run projects from my laptop drive. 

thank you!
