### ISSUE TITLE
Server not working on compiled app

### ISSUE THREAD

**Issue by rsodre** [keijiro/Funnel#7]
First, thanks for Funnel! This is exactly how a Syphon server should work inside a game.
I added Funnel to my camera, it works fine when I play in the Editor.
But when I build an app for distribution, the server is not created.
I can't find the Funnel.bundle anywhere inside the app, shouldn't it be copied there?

**Comment by keijiro** [comment]
Hmm... First of all, could you attach the player log file? (~/Library/Logs/Unity/Player.log) I'd like to investigate what's going on it.

**Comment by rsodre** [comment]
Sure, here it is. From it I can see Funnel is really missing.
[Player.log.txt](https://github.com/keijiro/Funnel/files/223028/Player.log.txt)

**Comment by keijiro** [comment]
Thanks! Okay, it seems like running in the 32-bit mode. Unfortunately, the new version of Funnel only supports 64-bit. Please try to change Architecture in Build Settings dialog to x86_64.

**Comment by rsodre** [comment]
Perfect!
Thanks!
