### ISSUE TITLE
Mouse Follow Issue

### ISSUE THREAD

**Issue by PabloMontero** [keijiro/Funnel#9]
Hi,

I'm using a 'Follow Mouse' script to attach a Particle System to the position of the mouse along the screen.

However, when I activate Funnel, the mouse only moves limited from the left side to the center of the screen.

Any help? Thank you very much!

**Comment by keijiro** [comment]
I have no idea why Funnel influences mouse move. Could you send a minimum project that reproduces the issue?

**Comment by keijiro** [comment]
I'm closing this issue now. Feel free to reopen if you find further issues.

**Comment by PabloMontero** [comment]
Hi Keijiro, sorry for the late reply, I was travelling.

You can see this problem with Funnel in this project:

https://github.com/PabloMontero/Funnel-MouseFollow-Issue

Hope it helps to make Funnel fully functional with this MouseFollow kind scripts.
